matrix:
  include:
    -language: nodejs
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="ocaml-webworker:. ocaml-gist:."
  matrix:
  - PACKAGE="ocaml-webworker" DISTRO="alpine-3.5" OCAML_VERSION="4.06.0"
  - PACKAGE="ocaml-gist" DISTRO="alpine-3.5" OCAML_VERSION="4.06.0"
  - PACKAGE="ocaml-webworker" DISTRO="alpine-3.5" OCAML_VERSION="4.05.0"
  - PACKAGE="ocaml-gist" DISTRO="alpine-3.5" OCAML_VERSION="4.05.0"
  - PACKAGE="ocaml-webworker" DISTRO="alpine-3.5" OCAML_VERSION="4.04.2"
  - PACKAGE="ocaml-gist" DISTRO="alpine-3.5" OCAML_VERSION="4.04.2"
  - PACKAGE="ocaml-webworker" DISTRO="alpine-3.5" OCAML_VERSION="4.03.0"
  - PACKAGE="ocaml-gist" DISTRO="alpine-3.5" OCAML_VERSION="4.03.0"
  - PACKAGE="ocaml-webworker" DISTRO="alpine-3.5" OCAML_VERSION="4.02.3"
  - PACKAGE="ocaml-gist" DISTRO="alpine-3.5" OCAML_VERSION="4.02.3"
# notifications:
#   webhooks:
#     urls:
#       - https://webhooks.gitter.im/e/6ee5059c7420709f4ad1
#     on_success: change
#     on_failure: always
#     on_start: false
